from .hero_comparison import Hero, Heroes

allHeroes: list[str] = [
    "Ana",
    "Ashe",
    "Baptiste",
    "Bastion",
    "Blank",
    "Blank",
    "Brigitte",
    "Cassidy",
    "D.Va",
    "Doomfist",
    "Echo",
    "Genji",
    "Hanzo",
    "Junker Queen",
    "Junkrat",
    "Kiriko",
    "Lucio",
    "Mei",
    "Mercy",
    "Moira",
    "Orisa",
    "Pharah",
    "Ramattra",
    "Reaper",
    "Reinhardt",
    "Roadhog",
    "Sigma",
    "Sojourn",
    "Soldier 76",
    "Sombra",
    "Symmetra",
    "Torbjorn",
    "Tracer",
    "Widowmaker",
    "Winston",
    "Wrecking Ball",
    "Zarya",
    "Zenyatta",
]
