name: Build and Test Web Service
on:
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t t500-aggregator .
          docker run --entrypoint "poetry shell; python -m http.server " t500-aggregator
