name: docker build and push

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract and manipulate tag name
        id: extract_tag
        run: |
          CLEAN_TAG_NAME=${date +%Y%m%d}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "CLEAN_TAG_NAME=${CLEAN_TAG_NAME}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thearyadev0/top500-aggregator:${{ env.CLEAN_TAG_NAME }}
